apiVersion: apps/v1
kind: Deployment
metadata:
  name: readlogfile
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: readlogfile
        image: docker.io/tmouli/readlogfile
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: readlogfile-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 9090
    targetPort: 8080
    nodePort: 30001
